### ISSUE TITLE
Drone not moving and just wobbling

### ISSUE THREAD

**Issue by freestuffasd** [sieuwe1/Autonomous-Ai-drone-scripts#6]
I'm getting all parameters on OpenCV screen and also getting yaw command in mavlink console but drone not moving after takeoff and just wobbling

**Comment by freestuffasd** [comment]
Its giving very small movement I think I need to adjust PID yaw and roll  for my quad

**Comment by akshaydhame2001** [comment]
Even if I remove PID it's just wobbling and not movin. On screen and in console commands are right but no movement.

Also 
Negative X Ned velocity is giving yaw added and therefore showing circular movement

**Comment by freestuffasd** [comment]
use 2503 type mask to ignore_yaw in -Vx for Copter > 4.0
